# Generated by Django 6.0.1 on 2026-01-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_rename_texto_comentario_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaforo',
            name='autor',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.tema'),
        ),
        migrations.DeleteModel(
            name='BuzonSugerencia',
        ),
        migrations.DeleteModel(
            name='TemaForo',
        ),
    ]
