# Generated by Django 6.0.1 on 2026-01-17 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.IntegerField(help_text='Orden de aparición (1, 2, 3...)')),
            ],
        ),
        migrations.CreateModel(
            name='LeccionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video_archivo', models.FileField(upload_to='cursos/videos/')),
                ('puntos_recompensa', models.IntegerField(default=20)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='formacion.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opcion_a', models.CharField(max_length=200)),
                ('opcion_b', models.CharField(max_length=200)),
                ('opcion_c', models.CharField(max_length=200)),
                ('correcta', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formacion.leccionvideo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.leccionvideo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'leccion')},
            },
        ),
    ]
