# Generated by Django 6.0.1 on 2026-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresousuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='orden',
        ),
        migrations.AddField(
            model_name='leccionvideo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leccionvideo',
            name='puntos_recompensa',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='leccionvideo',
            name='video_archivo',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preguntatest',
            name='opcion_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntatest',
            name='opcion_b',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntatest',
            name='opcion_c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntatest',
            name='texto',
            field=models.CharField(max_length=300),
        ),
    ]
