# Generated by Django 6.0.1 on 2026-01-19 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0002_alter_progresousuario_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('opcion_a', models.CharField(max_length=100)),
                ('opcion_b', models.CharField(max_length=100)),
                ('opcion_c', models.CharField(max_length=100)),
                ('correcta', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_examen', to='formacion.modulo')),
            ],
        ),
    ]
