# Generated by Django 6.0.1 on 2026-01-17 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('Novato', 'Novato'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Maestro', 'Maestro')], default='Novato', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
